### ISSUE TITLE
Местене на текущия сайт като такъв за 2014 и правене на сайт за 2015

### ISSUE THREAD

**Issue by krokodilerian** [initLab/initfest#10]
В момента 2014 ни е main сайта, което значи, че няма как да се преименува и съответно няма как да се създаде този за 2015 (а не искаме да правим съвсем нов, идеята беше да живеем на multisite). Трябва текущия да се преименува и да е достъпен някъде (например 2014.openfest.org или openfest.org/2014) и новия да се вижда на 2015.openfest или openfest/2015 (и по начало да е така, за да избегнем тоя проблем следващата година).

**Comment by vlood** [comment]
Понеже работим с настройка за поддиректории, хубаво ще е да се направи пренасочване на всички заявки за поддомейни (или поне годишните) да се пращат към поддиректории. Крокич, пусни си задачка, ако прецениш.

Другото го виждам по следния начин:
- копиране на съдържанието от основния домейн към подсайт 2014.
- създаване на подсайт 2015 с някакво основно съдържание.
- шаблонът да има сменяем header image, за да може да се брандира различно за различните години.
- пренасочване на основния домейн към 2015.

**Comment by krokodilerian** [comment]
Redirect-ът е готов, за годините до 2016.
