### ISSUE TITLE
Local setup

### ISSUE THREAD

**Issue by krasimir** [initLab/initfest#21]
@ignisf @vlood sorry за тъпия въпрос, но бих искал да си сетъпна сайта локално с последните данни в базата. Та ще ми трябва dump на това, което имаме live. Не помня какъв точно беше workflow-a в wordpress в този случай. Та ако е възможно може ли да засилите един `.sql` файл към `info@krasimirtsonev.com`. Мерси.

**Comment by krokodilerian** [comment]
@krasimir , ще ти извадя един dump на базата след малко и ще ти го пратя.

**Comment by krasimir** [comment]
Супер!

**Comment by vlood** [comment]
Локално ако си сложиш в конфигурационния файл WP_HOME & WP_SITEURL със
стойности http://localhost/tamkadeto, ще си спестиш известни замествания в
базата (щото има абсолютни пътища).

On Fri, Oct 16, 2015 at 2:47 PM, Krasimir Tsonev <notifications@github.com>
wrote:

> Супер!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/initLab/initfest/issues/21#issuecomment-148693217>.
>



-- 
** Simplicity*
  More time for enjoying life, less for emailing.
  Please, adopt the Email Charter - emailcharter.org

**Comment by krasimir** [comment]
@vlood: а супер, това ми трябваше.
